### ISSUE TITLE
Word counter pegged at 500 even when the limit is set higher

### ISSUE THREAD

**Issue by johnblommers** [dhbradshaw/thunderwriter#1]
To reproduce:
1. Double-click the canvas to bring up the settings.
2. Change the word count goal to 1000.
3. Click Submit.
4. Clear all text from the canvas.
5. Select more than 500 words of  text from another source.
6. Paste that text into the canvas
7. Note that the display reads **500 / 1000**

The expected behavior in my opinion is that the word counter should display the actual word count and not be capped at 500.

**Comment by dhbradshaw** [comment]
Hmm, I think that what is happening is that onChange, which handles word counting, isn't being triggered by copy and paste.  I imagine there's a paste event I could trigger on as well.

**Comment by dhbradshaw** [comment]
I'm having trouble recreating this one.  What browser and system are you on?

**Comment by johnblommers** [comment]
My system is Mac OS 10.11.6 (El Capitan). The web browser is Google Chrome Version 60.0.3112.50 (Official Build) beta (64-bit).

However the latest build in which you fixed the path also automagically fixed this problem. Indeed I can confirm that the word count is very accurate. I cannot reproduce it anymore so feel free to close this issue.
