### ISSUE TITLE
Thunderwriter won't work because of leading slashes in path names.

### ISSUE THREAD

**Issue by johnblommers** [dhbradshaw/thunderwriter#2]
Following the new build instructions we created a developmental build, moved the `build` folder to `~/Sites` on OS X El Capitan, opened file permissions for the web server, and pointed the web browser at `http://localhost/~johnb/build/index.html`.  We get only a purple empty window in Google Chrome.

A peek at the `index.html` reveals absolute paths for:
* /manifest.json
* /favicon.ico
* /static/css/main.65027555.css
* /static/js/main.34f2f033.js

The fix is simply to remove the leading slashes. I understand that the build files are meant to be dropped into the web server's documentroot but that is not my practice. I like to keep the little web pages I use in their own folders.

Please consider the following. Either:
* remove the leading slashes in the sources, or
* document how to build Thunderwriter so it will work out of its containing folder.

**Comment by dhbradshaw** [comment]
Yeah, that's standard for create-react-app apps.  I think I can solve it by setting the homepage flag on the package.json.

**Comment by dhbradshaw** [comment]
Ok, I added a homepage='.' flag to the package.json.  Let me know if that solves the problem for you.

**Comment by johnblommers** [comment]
Yes that solves the problem perfectly.
