### ISSUE TITLE
Misleading git clone instruction

### ISSUE THREAD

**Issue by johnblommers** [dhbradshaw/thunderwriter#3]
The installation instructions indicate to do a `git clone` but this happens:
```
git clone git@github.com:dhbradshaw/thunderwriter.git
Cloning into 'thunderwriter'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
But that does not work for me, I suspect because I'm not configured as a member and I don't have the necessary SSH cryptographic key. No matter. The following works fine for me:

```
git clone https://github.com/dhbradshaw/thunderwriter.git
```

**Comment by dhbradshaw** [comment]
Ok, I've replaced the ssh instructions with https instructions to reach a broader audience
