### ISSUE TITLE
Document how to pkg Thunderwriter as an executable application

### ISSUE THREAD

**Issue by johnblommers** [dhbradshaw/thunderwriter#6]
Would you consider the feasibility of documenting the process for converting Thunderwriter into an application using [pkg](https://www.npmjs.com/package/pkg)? `pkg`  is supposed to convert any Node.js application into a standalone application. 

The benefit is that anybody can run Thunderwriter on their platform of choice, even on ARM.

**Comment by dhbradshaw** [comment]
John, pkg looks pretty cool.  But I'm not sure I understand: why can't anyone just run it on ARM already?  Any web browser can run the application code because it's just html and javascript.

**Comment by johnblommers** [comment]
You are of course quite correct. I'm thinking in terms of the naive user who prefers the simplicity to run a native app. Plus it would be a fun and an interesting use for `pkg`. 

There is a rather neat Markdown editor called [Laverna](https://github.com/Laverna/laverna/releases) that is distributed as a desktop app. I prefer to run it that way. IIRC the famous [Atom](http://atom.io) editor is also distributed as a native application.

At any rate please consider this as a suggestion, no pressure :smile:

**Comment by johnblommers** [comment]
Based on your [detailed explanation](http://www.kboards.com/index.php/topic,253046.msg3525449.html#msg3525449) over at KBoards let me retract my suggestion, as it makes no sense under new light.

**Comment by dhbradshaw** [comment]
Okay, I think I'll close this then.  

Still, thanks for your thought and feedback and for pointing out some interesting packages.  These could be interesting down the road if we need access to local files, for example.
